export const translations = {
    en: {
        login: 'Login',
        email: 'Email',
        password: 'Password',
        welcome: 'Welcome Back',
        loginSubtitle: 'Sign in to continue your conversations',
        chatHistory: 'Chat History',
        newChat: 'New Chat',
        search: 'Search conversations...',
        send: 'Send',
        typeMessage: 'Type your message...',
        logout: 'Logout',
        language: 'Language',
        searchMessages: 'Search messages...',
        noResults: 'No results found',
        today: 'Today',
        yesterday: 'Yesterday',
        thisWeek: 'This Week',
        older: 'Older',
    },
    de: {
        login: 'Anmelden',
        email: 'E-Mail',
        password: 'Passwort',
        welcome: 'Willkommen zurück',
        loginSubtitle: 'Melden Sie sich an, um Ihre Gespräche fortzusetzen',
        chatHistory: 'Chatverlauf',
        newChat: 'Neuer Chat',
        search: 'Gespräche durchsuchen...',
        send: 'Senden',
        typeMessage: 'Nachricht eingeben...',
        logout: 'Abmelden',
        language: 'Sprache',
        searchMessages: 'Nachrichten durchsuchen...',
        noResults: 'Keine Ergebnisse gefunden',
        today: 'Heute',
        yesterday: 'Gestern',
        thisWeek: 'Diese Woche',
        older: 'Älter',
    },
};



